package com.ebest.frame.baselib.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ebest.frame.baselib.table.Form;
import com.ebest.frame.baselib.table.Measure;
import com.ebest.frame.baselib.table.Student;

import com.ebest.frame.baselib.greendao.FormDao;
import com.ebest.frame.baselib.greendao.MeasureDao;
import com.ebest.frame.baselib.greendao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig formDaoConfig;
    private final DaoConfig measureDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final FormDao formDao;
    private final MeasureDao measureDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        formDaoConfig = daoConfigMap.get(FormDao.class).clone();
        formDaoConfig.initIdentityScope(type);

        measureDaoConfig = daoConfigMap.get(MeasureDao.class).clone();
        measureDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        formDao = new FormDao(formDaoConfig, this);
        measureDao = new MeasureDao(measureDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(Form.class, formDao);
        registerDao(Measure.class, measureDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        formDaoConfig.clearIdentityScope();
        measureDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public FormDao getFormDao() {
        return formDao;
    }

    public MeasureDao getMeasureDao() {
        return measureDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
